version: "3.8"
services:
  detector-api:
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./app:/app
    container_name: detector-api
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
